-- BASE DE DATOS CHAT

CREATE TABLE USUARIOS
(
	ID_USUARIO INT AUTO_INCREMENT NOT NULL ,      
    NICK VARCHAR (20) NOT NULL,
	EMAIL VARCHAR (60) NOT NULL,
	ESTADO VARCHAR (20) DEFAULT 'Disponible',
    TELEFONO INT (10),
    IMAGEN_USUARIO VARCHAR (60),
    PASS VARCHAR (20) NOT NULL,
    ULTIMO_MENSAJE_LEIDO INT NOT NULL DEFAULT 0,

	
    CONSTRAINT UQ_EMAIL_USUARIOS UNIQUE (EMAIL),
    
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO)
);


CREATE TABLE GRUPOS
(
	ID_GRUPO INT AUTO_INCREMENT NOT NULL,      
    NOMBRE_GRUPO VARCHAR (20) NOT NULL,
    ID_ADMINISTRADOR_GRUPO INT (10),
    IMAGEN_GRUPO VARCHAR (60),
    
    CONSTRAINT PK_GRUPOS PRIMARY KEY (ID_GRUPO),
    
    CONSTRAINT FK_GRUPOS_USUARIO FOREIGN KEY (ID_ADMINISTRADOR_GRUPO)
		REFERENCES USUARIOS (ID_USUARIO)
);


CREATE TABLE PERTENECER
(
	ID_USUARIO INT NOT NULL ,      
  	ID_GRUPO INT NOT NULL , 
        
    CONSTRAINT PK_PERTENECER PRIMARY KEY (ID_USUARIO , ID_GRUPO),
    
     CONSTRAINT FK_PERTENECER_USUARIO FOREIGN KEY (ID_USUARIO)
		REFERENCES USUARIOS (ID_USUARIO),
    
     CONSTRAINT FK_PERTENECER_GRUPO FOREIGN KEY (ID_GRUPO)
		REFERENCES GRUPOS (ID_GRUPO)
);

-- LOS MENSAJES NO PUEDEN CONTENER MAS DE 100 CARACTERES NI PUEDEN SER NULOS.
CREATE TABLE MENSAJES
(     
  	ID_MENSAJE INT AUTO_INCREMENT NOT NULL ,    
    FECHA DATE,
    TEXTO VARCHAR (100) NOT NULL,
    
    CONSTRAINT PK_MENSAJES PRIMARY KEY (ID_MENSAJE)    
);


CREATE TABLE ENVIAR_MENSAJE_INV
(     
  	ID_MENSAJE INT NOT NULL ,    
	ID_USUARIO_EMISOR INT NOT NULL , 
    ID_USUARIO_RECEPTOR INT NOT NULL , 
    
    CONSTRAINT PK_MENSAJES_INV PRIMARY KEY (ID_MENSAJE , ID_USUARIO_EMISOR , 
		ID_USUARIO_RECEPTOR),
    
     CONSTRAINT FK_ENVIAR_INV_MENSAJE FOREIGN KEY (ID_MENSAJE)
		REFERENCES MENSAJES (ID_MENSAJE),
    
     CONSTRAINT FK_ENVIAR_INV_EMISOR FOREIGN KEY (ID_USUARIO_EMISOR)
		REFERENCES USUARIOS (ID_USUARIO),
    
    CONSTRAINT FK_ENVIAR_INV_RECEPTOR FOREIGN KEY (ID_USUARIO_RECEPTOR)
		REFERENCES USUARIOS (ID_USUARIO)
);


CREATE TABLE ENVIAR_MENSAJE_GRUPO
(     
  	ID_MENSAJE INT NOT NULL,    
	ID_USUARIO INT NOT NULL , 
    ID_GRUPO INT NOT NULL , 
        
    CONSTRAINT PK_MENSAJES_GRUPO PRIMARY KEY (ID_MENSAJE , ID_USUARIO , 
		ID_GRUPO),
    
     CONSTRAINT FK_ENVIAR_GRUPO_MENSAJES FOREIGN KEY (ID_MENSAJE)
		REFERENCES MENSAJES (ID_MENSAJE),
    
     CONSTRAINT FK_ENVIAR_GRUPO_USUARIOS FOREIGN KEY (ID_USUARIO)
		REFERENCES USUARIOS (ID_USUARIO),
    
    CONSTRAINT FK_ENVIAR_GRUPO_GRUPOS FOREIGN KEY (ID_GRUPO)
		REFERENCES GRUPOS(ID_GRUPO)
);