-- BASE DE DATOS CHAT

CREATE TABLE USERS
(
	ID_USER INT AUTO_INCREMENT NOT NULL ,      
    NICK VARCHAR (20) NOT NULL,
	STATUS VARCHAR (20) DEFAULT 'Disponible',
    PHONE INT (10) NOT NULL,
    USER_IMAGE VARCHAR (100),
    PASSWORD VARCHAR (20) NOT NULL,
    LAST_RECIEVED_MESSAGE INT NOT NULL DEFAULT 0,

	
    CONSTRAINT UQ_PHONE_USERS UNIQUE (PHONE),
    CONSTRAINT PK_USERS PRIMARY KEY (ID_USER)
);


CREATE TABLE GRUPOS
(
	ID_GROUP INT AUTO_INCREMENT NOT NULL,      
    NAME_GROUP VARCHAR (20) NOT NULL,
    ID_GROUP_ADMIN INT (10),
    IMAGE_GROUP VARCHAR (60),
    
    CONSTRAINT PK_GROUPS PRIMARY KEY (ID_GROUP),
    
    CONSTRAINT FK_GROUPS_USERS FOREIGN KEY (ID_GROUP_ADMIN)
		REFERENCES USERS (ID_USER)
);


CREATE TABLE BELONG
(
	ID_USER INT NOT NULL ,      
  	ID_GROUP INT NOT NULL , 
        
    CONSTRAINT PK_BELONG PRIMARY KEY (ID_USER , ID_GROUP),
    
     CONSTRAINT FK_BELONG_USER FOREIGN KEY (ID_USER)
		REFERENCES USERS (ID_USER),
    
     CONSTRAINT FK_BELONG_GROUP FOREIGN KEY (ID_GROUP)
		REFERENCES GRUPOS (ID_GROUP)
);

-- LOS MENSAJES NO PUEDEN CONTENER MAS DE 100 CARACTERES NI PUEDEN SER NULOS.
CREATE TABLE MESSAGES
(     
  	ID_MESSAGE INT AUTO_INCREMENT NOT NULL ,    
    DATE_MESSAGE DATE,
    TEXT VARCHAR (100) NOT NULL,
    
    CONSTRAINT PK_MESSAGES PRIMARY KEY (ID_MESSAGE)    
);


CREATE TABLE SEND_INDIVIDUAL_MESSAGE
(     
  	ID_MESSAGE INT NOT NULL ,    
	ID_USER_SENDER INT NOT NULL , 
    ID_USER_RECEIVER INT NOT NULL , 
    
    CONSTRAINT PK_MESSAGES_INV PRIMARY KEY (ID_MESSAGE , ID_USER_SENDER , 
		ID_USER_RECEIVER),
    
     CONSTRAINT FK_SEND_INV_MESSAGE FOREIGN KEY (ID_MESSAGE)
		REFERENCES MESSAGES (ID_MESSAGE),
    
     CONSTRAINT FK_SEND_INV_SENDER FOREIGN KEY (ID_USER_SENDER)
		REFERENCES USERS (ID_USER),
    
    CONSTRAINT FK_SENDER_INV_RECEIVER FOREIGN KEY (ID_USER_RECEIVER)
		REFERENCES USERS (ID_USER)
);


CREATE TABLE SEND_MESSAGE_GROUP
(     
  	ID_MESSAGE INT NOT NULL,    
	ID_USER INT NOT NULL , 
    ID_GROUP INT NOT NULL , 
        
    CONSTRAINT PK_MESSAGES_GROUP PRIMARY KEY (ID_MESSAGE , ID_USER , 
		ID_GROUP),
    
     CONSTRAINT FK_SEND_GROUP_MESSAGES FOREIGN KEY (ID_MESSAGE)
		REFERENCES MESSAGES (ID_MESSAGE),
    
     CONSTRAINT FK_SEND_GROUP_USERS FOREIGN KEY (ID_USER)
		REFERENCES USERS (ID_USER),
    
    CONSTRAINT FK_SEND_GROUP_GRUPOS FOREIGN KEY (ID_GROUP)
		REFERENCES GRUPOS(ID_GROUP)
);